actioncable:
  - "actioncable/**/*"
actionmailer:
  - "actionmailer/**/*"
actionpack:
  - "actionpack/**/*"
routing:
  - "actionpack/**/*routing*"
actionview:
  - "actionview/**/*"
activejob:
  - "activejob/**/*"
activemodel:
  - "activemodel/**/*"
activerecord:
  - "activerecord/**/*"
MySQL:
  - "activerecord/**/*mysql*"
PostgreSQL:
  - "activerecord/**/*postgresql*"
enum:
  - "activerecord/**/*enum*"
activestorage:
  - "activestorage/**/*"
activesupport:
  - "activesupport/**/*"
rails-ujs:
  - "actionview/app/assets/javascripts/rails-ujs*/*"
railties:
  - "railties/**/*"
engines:
  - "railties/lib/rails/engine/**/*"
  - "railties/test/railties/**/*engine*"
docs:
  - "guides/**/*"
asset pipeline:
  - "guides/source/asset_pipeline.md"
ci issues:
  - "ci/**/*"
security:
  - "**/*/cross_site*"
  - "**/*/csrf*"
  - "**/*/cookies*"
  - "**/*/content_security_policy*"
  - "guides/**/*/security*"
  - "activesupport/**/*/message_verifier*"
  - "activesupport/**/*/security_utils*"
  - "actionpack/**/*/request_forgery*"
  - "actionpack/**/*/cookie_store*"
  - "actionview/**/*/sanitize_helper*"
  - "activemodel/**/*/secure_password*"
  - "activerecord/**/*/secure_token*"
  - "activerecord/**/*/sanitize_test*"
  - "activerecord/**/*/sanitization*"
i18n:
  - "**/*i18n*"
