language: ruby
script: 'ci/travis.rb'
before_install:
  - travis_retry gem install bundler
  - "rvm current | grep 'jruby' && export AR_JDBC=true || echo"
env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=aj"
    - "GEM=am,amo,as,av"
    - "GEM=ar:mysql"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
rvm:
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
  fast_finish: true
bundler_args: --path vendor/bundle --without test
services:
  - memcached
  - redis
  - rabbitmq
addons:
  postgresql: "9.3"

