name: Label Actions

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
