name: RuboCop

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: rubocop

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
        cache-version: 6-1-stable-1

    - name: Run RuboCop
      run: bundle exec rubocop --parallel
